### ISSUE TITLE
Automated releases stopped working

### ISSUE THREAD

**Issue by fermanjj** [arlyon/async-stripe#418]
### Describe the bug

It looks like automated releases to crates.io stopped working a few months ago

https://github.com/arlyon/async-stripe/actions/workflows/release.yml

### To Reproduce

See workflows in Github

### Expected behavior

I think this workflow publishes a new version to crates.io

### OS

N/A

### Rust version

N/A

### Library version

all

### API version

N/A

**Comment by arlyon** [comment]
I have been meaning to find time to resolve this. Seems to be related to `semantic-release-cargo`

**Comment by arlyon** [comment]
This is now fixed, TY for the flag!

**Comment by fermanjj** [comment]
Although the releases are now seemingly working, for some reason I'm not seeing the version updated in [Crates.io](https://crates.io/crates/async-stripe). It's still showing 0.22.2 (released on May 11, 2023).

Perhaps due to an [undetected change](https://github.com/arlyon/async-stripe/actions/runs/6148896792/job/16683626823#step:4:61)?

**Comment by fermanjj** [comment]
New version is there! ty 🙏
